### ISSUE TITLE
deb package : Dependency Update needed

### ISSUE THREAD

**Issue by frantic1048** [Kreogist/Mu#11]
**Distro** : XUbuntu
**Date** : Thursday, June 18, 2015

    Dependency is not satisfiable : libavcodec54

快点来更新包呀～

**Comment by Harinlen** [comment]
先解释一下什么鬼。。。。

**Comment by iyzsong** [comment]
自己编译 deb 包的话，这种问题不可避免。
可以：
- 用户自己编译(推荐 <_<)
- 整个 PPA

**Comment by Harinlen** [comment]
是时候整个PPA了。
让用户自己编译的话，感觉会被打死OTZ

**Comment by Harinlen** [comment]
PPA已经搞定了，这个issue就算是终结了吧。

**Comment by frantic1048** [comment]
嗯，编译啥的也都搞定了呢 ლ(╹◡╹ლ)
