### ISSUE TITLE
Mu支持解码Silk格式的音频嘛。。

### ISSUE THREAD

**Issue by AG3** [Kreogist/Mu#12]
就是那个skype出的格式。。。

**Comment by Harinlen** [comment]
不支持，我没有在后缀里加这个格式，它应该就没有被添加的可能性。
Windows、Mac下的bass没有这个格式的插件，所以可能性也不大。
Linux下用的Phonon就看RP了。要是系统有这个解码就好。
然而……这个格式是什么……0 0……为何没听说过0 0

**Comment by Harinlen** [comment]
等下，好像是支持的？
Windows下的Slik个那个用的编码是Opus的，如果是Opus的话，那么Windows和Mac下就是支持的。Linux下还是看系统怎么配置的了。
