### ISSUE TITLE
更多歌词源

### ISSUE THREAD

**Issue by miaolapd** [Kreogist/Mu#14]
取自FB2K的ESLyric插件的JS脚本
比之前的多了百度和酷狗的歌词源，天天动听的好像也更新了版本
里面还有酷狗的KRC格式转换的脚本
有需要的话可以参考一下
链接: http://pan.baidu.com/s/1o6GOL8Q#icz4
密码: icz4

**Comment by Harinlen** [comment]
非常感谢，等最近期末考试完了后开始着手移植。
之前的脚本非常感谢 :)

**Comment by Harinlen** [comment]
说来其实觉得百度的歌词搜索结果一直不靠谱……之前有看到过百度的歌词搜索，尝试了一下后果断删了。

**Comment by TongKuo** [comment]
试试 [Musixmatch 的 API](https://developer.musixmatch.com)？

**Comment by Harinlen** [comment]
嗯，这个可以试试看。不过这个API貌似是要$的？虽然现在是测试中？

**Comment by TongKuo** [comment]
Musixmatch 是我平时常用的歌词服务，开发 API 方面的东西我就不太清楚了😶，只是推荐一个可选的选项。

**Comment by Harinlen** [comment]
能剧透一下是怎么用的吗？是FB的插件之类的么？或者什么别的软件之类的？可以考虑嗅探挖掘一下怎么使用的。谢谢~~

**Comment by TongKuo** [comment]
Musixmatch 本身就是一个面向 end-user 的 web 服务：[musixmatch.com](https://www.musixmatch.com)。刚才提到的 API 只是官方为第三方应用提供的接口。

**Comment by Harinlen** [comment]
原来是这样。刚刚试用了一下，效果很棒，稍微冷门一点的曲子也能找到歌词。
然而这些歌词并不是LRC格式的啊？Musixmatch能提供LRC格式的歌词吗？

**Comment by Harinlen** [comment]
有关Musixmatch新建了一个issue #15 ，移步到那里继续讨论吧。

**Comment by Harinlen** [comment]
酷狗的歌词模块已经完成了，确实可用。（Commit的编号打错了，已经晕了）
百度的……额……鉴于最近它作恶多端而且确实不好用就不支持这个2货了。
天天动听的代码也已经更新完毕了。
以上

**Comment by Harinlen** [comment]
酷狗的这个库太好用了，赞个

**Comment by miaolapd** [comment]
天天动听的歌词源脚本再次更新到0.1.2，不知道更新了什么，你看看有没什么代码需要更新的~~~
链接: http://pan.baidu.com/s/1hqpXH7u#x53t 密码: x53t

**Comment by Harinlen** [comment]
好，之后我看一下

**Comment by Harinlen** [comment]
仔细比对了一下，除了最前面的注释从0.0.6变成了0.1.2，后面的都没有变……

**Comment by miaolapd** [comment]
╮(╯▽╰)╭

**Comment by Harinlen** [comment]
@miaolapd 不知道大大这些脚本都是从哪里来的啊？感觉最近QQ音乐的那个脚本有更新，有必要继续跟进更新一下

**Comment by miaolapd** [comment]
@Harinlen 
我是从Asion汉化的fb2k里找到的，不过现在Asion不汉化了，我也不知道以后要去哪里找了，这个是Asion汉化的fb2k 1.3.14里的歌词源脚本：
链接: https://pan.baidu.com/s/1o8SGDpo 密码: tv8k

下面的是ESLyric插件作者所收集的歌词源脚本：
https://drive.google.com/drive/folders/0B2KhsZAUDf9CMFUtOTZJRXV2Z2M

**Comment by Harinlen** [comment]
@miaolapd 非常感谢，今天刚刚把所有的下载模块改成了异步模式下载，在比较好的网速条件下基本上可以做到秒级下载了，准备趁着这个机会更新一下脚本。

**Comment by Harinlen** [comment]
@miaolapd QQ音乐的歌词源已经更新了。可惜的是TTPod的已经没法使用了，已经废弃。
