### ISSUE TITLE
Translation file location（翻译文件位置）

### ISSUE THREAD

**Issue by Harinlen** [Kreogist/Mu#17]
Normally, the language translation file should be put at `/usr/share/locale/zh_CN/LC_MESSAGES/mu.qm`. mu should find the language translation file there. In the `src/sdk/knlocalemanager.cpp`, it's reading accoring to the configuration at `src/resource/public/language.json`. The binary will check the file at the Language directory with the language name. It doesn't make sense.

一般语言文件存在这里，`/usr/share/locale/zh_CN/LC_MESSAGES/mu.qm`。使 mu 读取它就可以了。我看 `src/sdk/knlocalemanager.cpp` 是根据 `src/resource/public/language.json` 配置，读取可执行文件当前目录下的 Language/语言/语言.qm。这好像不太合理。

**Comment by 1dot75cm** [comment]
> 其实……我不太了解Linux下各个文件都应该放在哪里。

Linux 有[文件系统层次标准](http://www.pathname.com/fhs/)，一般都按照该标准存储文件。

我简单修改了 `src/sdk/knlocalemanager.cpp`，使 mu 能够从 `/usr/share/locale/zh_CN/LC_MESSAGES/mu.qm` 读取翻译。关于国旗，建议直接作为资源链接至可执行文件。

**Comment by Harinlen** [comment]
直接作为资源链接太大了，而且不利于扩展，现在这种做法其实也是一种折中的做法。
这个模块我会在最近的版本修改成为从该文件夹获取。

**Comment by Harinlen** [comment]
不过其实从~/.kreogist里面对应位置读取也可以接受？

**Comment by 1dot75cm** [comment]
放到 ~/.kreogist 里就没法安装了。资源文件一般不修改，所以放到 `/usr/share/mu/` 这样的目录里比较好。比如：

- `/usr/share/mu/locale/*.qm *.png`  保存翻译文件
- `/usr/share/mu/plugin/`   保存插件之类的

**Comment by Harinlen** [comment]
这里本来就是想做成可修改的，所有的这些翻译准备允许用户在安装后再添加、删除、修改的

**Comment by 1dot75cm** [comment]
有兴趣的人自然会帮助翻译，并提交 PR。 可以做成读取这两个地方，方便用户翻译时测试。

- ~/.kreogist/locale/*.qm
- /usr/share/mu/locale/*.qm

**Comment by Harinlen** [comment]
了解，我将尽快做出改动。然而最近几天可能暂时无法作出变更。
（现在还在折腾GStreamer。Playbin什么的简直坑，所以转而研究自定义pipeline。然而被各种不和规范的代码坑的不要不要的……正在爬各种别人的项目中）

**Comment by 1dot75cm** [comment]
:+1:

**Comment by amazingfate** [comment]
参考baka-mplayer,放在/usr/share/mu/translations:
https://github.com/u8sand/Baka-MPlayer/blob/master/src%2FBaka-MPlayer.pro

**Comment by Harinlen** [comment]
好的，这个项目之前也看到过，收到了很大的帮助。谢谢～～～

**Comment by Harinlen** [comment]
针对Linux已经修改成从下列两个地方获取：

- /usr/share/Kreogist/mu/Language
- ～/.kreogist/mu/Language

**Comment by 1dot75cm** [comment]
好滴，感谢修复

**Comment by Harinlen** [comment]
这里才是要感谢反馈呢 :)
