### ISSUE TITLE
在Ubuntu 16.4下運行。。會導致其他應用變卡

### ISSUE THREAD

**Issue by yonjar** [Kreogist/Mu#19]
嗯，就是這麼奇怪，運行了一會後，其他應用就變卡了，而Mu本身依然流暢。
下面是配置：

![瀏覽圖](https://public.lightpic.info/image/B1A9_573C21090.jpg)

**Comment by Harinlen** [comment]
這個問題還是頭一次遇到啊。這個配置也並不低就是了。
Ubuntu 16.04下目前還沒有做過任何測試。您是自己編譯的Mu嘛？

**Comment by Harinlen** [comment]
抱歉，最近考試和作業特別多，回復和處理速度有點慢，請見諒 :)

**Comment by yonjar** [comment]
下載的是官網的 “ 适用于 64 位 Ubuntu 15.10 的 μ（deb, 2.9 MB）”
我就只是一個喜歡嚐鮮的小白，所以問題出在哪裏我也不太懂 : {

**Comment by frantic1048** [comment]
有用进程管理器之类的工具查看过运行 Mu 的时候的系统状况么？
比如看看 Mu 的处理器占用、以及内存占用是否不科学之类的。

**Comment by yonjar** [comment]
之前因爲這個問題有幾天沒用過Mu，現在好像又正常了，再觀察一下先

**Comment by Harinlen** [comment]
對於Windows和Mac版本發現了潛在的內存洩露的問題。Linux上應該不存在這個問題（因為使用的是GStreamer而不是bass）。
如果存在任何問題請在這裡反饋一下吧。感謝支持的說 :)
（滾去趕作業了）

**Comment by Harinlen** [comment]
近期咱會盡快在16.04上進行測試的，周圍已經有從16.04退回15.10的人了OTZ

**Comment by Harinlen** [comment]
今天在準備新的版本的時候16.04上嘗試了一下，沒能重現這個bug。
很快將會發布0.9.9.2版本，您可以嘗試一下看看是否還有這個問題。

**Comment by yonjar** [comment]
那应该是我的电脑抽了..

**Comment by yonjar** [comment]
那应该是我的电脑抽了..

**Comment by Harinlen** [comment]
额……或许现在应该在一些老的机型上做测试了。
目前测试过最低的机器是Mac Mini 2014

**Comment by Harinlen** [comment]
新的版本已经公开了，尝试一下在16.04下编译的deb包能否解决这个问题？

**Comment by yonjar** [comment]
@Harinlen 更新後，發現動畫效果變流暢了，但鼠標懸停在歌名上彈出專輯詳情依然有卡頓，  
然後用了三個小時，cpu使用率從33%上下升到48%上下，內存使用倒是能穩定在115Mb上下。

**Comment by Harinlen** [comment]
懸停卡頓的問題受限於預覽要加載文件，所以這個問題可能解決不能。或許只能換一種策略來解決這個問題了。（嗯大概有想法了）

CPU使用率在Windows下使用Intel的性能檢測工具我測得的數據是迷你模式最高0.7%，在顯示窗口的情況下正常播放應該也能維持在7%以下。除非是添加文件。可能也是受限於CPU的性能問題。CPU的性能確實應該持續優化。這也是咱一直煩惱的問題。

不過幸好確認了不是代碼本身哪裡有什麼嚴重的bug。感謝您的反饋，我也將繼續在優化上下功夫的說-w-
