### ISSUE TITLE
在 Backbox 上无法设置头像 / Cannot set avatar on Backbox

### ISSUE THREAD

**Issue by Harinlen** [Kreogist/Mu#23]
现收到一个可能的bug报告，有用户在Xfce环境下的系统上无法选择头像，请尽快确认这个问题。
系统版本：Backbox 4.6
系统上游发行版：Ubuntu 14.04 LTS
系统内核：4.2.0

Now we have received a potential bug report: the reporter cannot set avatar under Xfce DE. Please ensure this is a bug or not ASAP.
OS: Backbox 4.6
Upstream: Ubuntu 14.04 LTS
Kernel version: 4.2.0

**Comment by yangjinhe** [comment]
不是blackbox  是backbox

**Comment by Harinlen** [comment]
抱歉，昨天没有看清楚，修正了www

**Comment by Harinlen** [comment]
问题不能重现，关闭。

The issue cannot be reproduced, closed.
