### ISSUE TITLE
同时添加 .cue 和对应音频文件的时候，忽略 .cue 对应的那个源文件 

### ISSUE THREAD

**Issue by frantic1048** [Kreogist/Mu#24]
比如一个文件夹下有 `album.ape` 和 `album.cue`，把整个文件夹拖进播放器的话，除了会添加 .cue 里面记录的每一个单独的轨道作为一首歌之外，还会额外添加进 `album.ape`。

这种情形是否可以忽略掉后面那个 .cue 对应的整块专辑的文件？

**Comment by Harinlen** [comment]
在项目之初考虑过，但是因为这样的话需要查整个表啊，所以这个当初就没写。
现在的添加文件里面，存在这样一个的优化机制：如果cue里面记录的文件并没有找到，那么直接搜索当前文件夹下的同名可播放类型文件作为这个文件。这样如果要是同一个cue下存在同文件名但不同拓展名的两个播放文件，选择字母序小的那个。（现在发现一个cue里面写的是CDImage.flac然而实际上是wav，很多文件都存在这个问题）那么在这个情况下，应当忽略哪个文件呢？
除此以外，在播放cue的时候，也经历过就希望播放那个APE但是播放器还是强行根据CUE分轨的情况。（AirPlay 3）

所以鉴于性能和实际实现时候的问题，这个功能并没有添加到里面。要是有办法解决这两个问题的话，我会抽时间去实现的。

**Comment by Harinlen** [comment]
现在在媒体库内，支持忽略CUE的源文件了。
当添加到播放列表时，仍然会将源文件和CUE文件全部添加进去。（这个感觉更合理）
