### ISSUE TITLE
前来问候

### ISSUE THREAD

**Issue by G-g-beringei** [Kreogist/Mu#26]
这几天买了新的音乐播放设备，想下个播放器来着，突然想起了这个，当时是在deepin用的，感觉非常好（大概是三年以前？）。这次到处找居然没找到，后来又在deepin的商店里找到了项目地址，本以为已经死了（商店里好像还是几年前的版本），没想到作者14天前还提交过来着，有点感动啊，特来问候一下。希望作者继续加油。

**Comment by Harinlen** [comment]
非常感谢，最近因为毕业原因更新速度很慢，其实新版本准备发布然而一只因为个人问题导致没有啥时间。新的功能也在计划和更新，不过速度会比较慢。估计毕业后速度会快点。
