### ISSUE TITLE
Would reset system volume when switching songs on Linux

### ISSUE THREAD

**Issue by hosiet** [Kreogist/Mu#29]
On Linux desktop with pulseaudio, Mu would reset system sound volume every time I switch the song. This is very annoying and should be considered as a bug.

**Comment by Harinlen** [comment]
This could be a bug. I will test it later on.

**Comment by Harinlen** [comment]
In the latest version of the repository, the backend has changed from GStreamer to MPV. It won't use the GStreamer backend volume control anymore, this bug should be fixed.

I am looking forward to your reply.

**Comment by hosiet** [comment]
I can confirm that this problem is fixed after the switch from gstreamer to mpv. Closing this issue.

Thanks!
