### ISSUE TITLE
Translation .qm files not built by default

### ISSUE THREAD

**Issue by hosiet** [Kreogist/Mu#31]
```bash
qmake .
make
```

在 Linux 系统下，如此操作将不会从 `.ts` 文件构建 `.qm` 文件，需要调查原因。

不是很熟悉 QMake， `src/src.pro` 中有 i18n{} 这一段，但不知为何貌似没起作用。

**Comment by Harinlen** [comment]
只是因为目前没有在config里加入i18n，在正式发布的时候会带上的。现在在手动测试一个翻译文件。

**Comment by frantic1048** [comment]
可以在 qmake 中传入 release 选项，这样构建就会有 i18n 部分了。类似这样：

```sh
qmake "CONFIG+=release" PATH_TO/mu.pro
make
```
参见：https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kreogist-mu#n47

**Comment by Harinlen** [comment]
其实只是之前在Qt Creator调试的时候顺手给注释了……
