### ISSUE TITLE
谈谈UX

### ISSUE THREAD

**Issue by MidoriYakumo** [Kreogist/Mu#4]
1. 在运行目录下创建配置文件和数据, 像个"绿色软件";
2. 没有Qt引以为豪的快捷键功能
3. 没有记录上次播放位置
4. 没有任何方法向播放列表添加

**Comment by Harinlen** [comment]
生成的媒体库现在已经可以移动。
现在已经配置文件固定保存在用户文件夹了。
想问一下……Qt的快捷键功能是？

**Comment by MidoriYakumo** [comment]
恩前几天已经看到了
Qt的QShortcut很好用的 http://doc.qt.io/qt-5/qshortcut.html

**Comment by MidoriYakumo** [comment]
![ss184](https://cloud.githubusercontent.com/assets/6872220/5602905/5f85ab80-93a7-11e4-9779-1cd54289b75f.png)
Qt有一组自由度极高的快捷键设置组件, 支持应用内和全桌面(KDE或者libqxt)的

**Comment by Harinlen** [comment]
QShortcut已经用了一部分了，但是到现在确实还没实现去按键盘操作。暂时只是为了调试方便加入了Ctrl+F搜索，剩下的功能都还没有对应的快捷键。
不过全键盘操作确实是个很有意思的功能点。可以挑战一下。

**Comment by MidoriYakumo** [comment]
以前用fb2k的时候基本上就是靠键盘操作的, 实在是方便

**Comment by Harinlen** [comment]
fb2k实在是太强大了，那个说成是终极目标都不为过啊。
最终能实现其一半的功能就已经很了不得了。
全键盘组合键映射这个可以考虑一下：

**Comment by Harinlen** [comment]
向播放列表里添加歌曲已经在最新的dev分支里面实现了。
记录上次播放这个可能要等到下次重构才能实现了。快捷键……很抱歉还要推迟一下……因为貌似Qt没有全局的快捷键。目前为止只知道怎么分平台进行设定，可能需要去写一个单独的库了。

**Comment by Harinlen** [comment]
Qt的快捷键功能现在已经在最新的主线分支里加入了。只是目前为止支持的快捷键比较少。允许用户对同一个功能设置四组快捷键。

**Comment by Harinlen** [comment]
记录上次播放位置这个功能已经在最新的主线分支里加入了。
