### ISSUE TITLE
fedora rpm

### ISSUE THREAD

**Issue by 1dot75cm** [Kreogist/Mu#9]
支持一下kreogist的作品。昨天在oschina看到介绍，连夜打包完成。
https://copr.fedoraproject.org/coprs/mosquito/myrepo/build/70499/
一会添加一下介绍信息。

**Comment by 1dot75cm** [comment]
已添加软件介绍 https://github.com/1dot75cm/myrepo

**Comment by Harinlen** [comment]
非常感谢！我现在就去更新网站链接。

**Comment by Harinlen** [comment]
辛苦您了~感谢您的支持~~

**Comment by 1dot75cm** [comment]
plasma下效果挺棒的，赞一个。
有个小问题，默认音量最大，只有设置过后才会写入配置。建议第一次使用时，默认音量最小。
另外，歌词的位置有点偏僻。

**Comment by Harinlen** [comment]
谢谢您的建议！
我们将在下一个版本内对这些问题进行改进。感谢您的支持！

**Comment by Harinlen** [comment]
默认音量当前已经调整为0.5了。
有关歌词位置这个问题，待主播放器界面出来的时候就会有大一点的歌词界面了。

**Comment by 1dot75cm** [comment]
赞，commit攒多了再更新一下包，测试看看。

**Comment by Harinlen** [comment]
嗯，很感谢您的支持。
不过其实dev是不用打包的。因为dev包括的很多功能可能是不稳定的。
您可以帮助我们跟踪跟新master分支即可。

**Comment by 1dot75cm** [comment]
好的～ 白天我改下

**Comment by Harinlen** [comment]
谢谢您的支持~~~

**Comment by 1dot75cm** [comment]
已将 mu 加入 Fedora 中文社区软件源，请更新 URL。
http://repo.fdzh.org/FZUG/
Spec：github.com/FZUG/repo/

另外，Linux 编译选项明确的添加 -m64 是出于什么原因？

**Comment by 1dot75cm** [comment]
@Harinlen

**Comment by Harinlen** [comment]
非常感谢您的协助！Fedora方面的更新辛苦您了！
Linux下明确添加 -m64 只是为了编译生成64位包方便于编译器侧重生成更好的64位代码。
如果生成32位包的话，那个开关就可以注释掉。

**Comment by Harinlen** [comment]
地址已经更新~非常感谢~

**Comment by 1dot75cm** [comment]
:+1:  -m64 或 -m32 打包时会自动根据 arch 添加。

**Comment by 1dot75cm** [comment]
还有一个关于 i18n 的问题。我还没看源码，是根据 LANG 相关变量判断当前系统语言，然后编译相关语言么？

**Comment by frantic1048** [comment]
那个是因为 0.9 的时候在 Lunux 下编译遇到了关于编 i18n 的问题，所以当时暂时关闭了那个开关

**Comment by Harinlen** [comment]
i18n那个原因其实是因为我写的pro和debian文件不知道为何折腾不出来。所以最后只有英文版。
其他的语言应该是都可以出来的，这一点我也在看qmake的文档。

**Comment by 1dot75cm** [comment]
一般语言文件存在这里，`/usr/share/locale/zh_CN/LC_MESSAGES/mu.qm`。使 mu 读取它就可以了。我看 `src/sdk/knlocalemanager.cpp` 是根据 `src/resource/public/language.json` 配置，读取可执行文件当前目录下的 Language/语言/语言.qm。这好像不太合理。

**Comment by Harinlen** [comment]
其实……我不太了解Linux下各个文件都应该放在哪里。恩，您的这个问题我已经单独建立了个问题issue。后面的跟进内容我会都放到#17.
